version: '2'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh:
    # ssh in den Container:   ssh localhost -l s3 -p 2205 -i docker_erp.key
    #
    erp-bpmn:
      #image: abas/pi-erp:latest
      image: nexus3.abas-usa.com:18001/abas-erp:latest
      container_name: "demo_app_erp"

      ports:
      - "2207:22"
      - "8003:80"
      - "6561:6550"
      - "48792:48392"

      environment:
      - ABAS_HOST
      - ABAS_GUI_PORT=48792

      # starteVersion muss wegen der Volltextsuche als User s3 gestartet werden
      # Als root-user gibt es sonst Probleme wegen dem ulimit der open files.
      user: s3
      hostname: dockerbau

    # nexus host for madep
    nexus:
      image: sonatype/nexus:oss
      container_name: "demo_app_nexus"
      ports:
      - "8080:8081"
