version: '3'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh:
    # ssh in den Container:   ssh localhost -l s3 -p 2205 -i docker_erp.key
    #
    erp:
      image: intra.registry.abas.sh/cloud-erp-neumand1:2016r4n13
      container_name: "erp"

      ports:
      - "${SSH_TEST_PORT:-2205}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${EDP_TEST_PORT:-6560}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"

      environment:
      - ABAS_HOST
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # starteVersion muss wegen der Volltextsuche als User s3 gestartet werden
      # Als root-user gibt es sonst Probleme wegen dem ulimit der open files.
      user: s3
      hostname: dockerbau

    nexus:
      image: sonatype/nexus:oss
      container_name: "nexus"
      ports:
        - "${NEXUS_TEST_PORT:-8081}:8081"
